server:
    port: 8003
spring:
    application:
        name: todos-data
    cloud:
        stream:
            bindings:
                onCreatedEvent:
                    destination: todoCreatedEvent
                onDeletedEvent:
                    destination: todoDeletedEvent
                onUpdatedEvent:
                    destination: todoUpdatedEvent
                fireCreatedEvent:
                    destination: todoCreatedEvent
    flyway:
        locations: 'classpath:/db/migration/h2'
    h2:
        console:
            enabled: true
    jpa:
        hibernate:
            ddl-auto: validate
management:
    endpoints:
        web:
            base-path: /ops
            exposure:
                include: '*'
logging:
  level:
    io.corbs: DEBUG